### ISSUE TITLE
Can't connect on secure port

### ISSUE THREAD

**Issue by dvand** [kevinohara80/elkington#5]
insecure connection works fine. Maybe an issue with old ssl versions or certificates on the XEP?

~/node $ node elktest.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at SecurePair.error (tls.js:1010:23)
    at CleartextStream.read [as _read](tls.js:462:17)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write](tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
pi@raspberrypi ~/node $

**Comment by kevinohara80** [comment]
Interesting. TBH, it's been a while since I played with this. I'll see if I can find some time tonight to look at this and try it out.

**Comment by dvand** [comment]
I actually got it to work.

First thing is I was connecting to the secure port but not using a
password.

Second thing is I set some of the tls connection options.

**Comment by awmcclain** [comment]
What were your TLS connection options? I'm running into the same problem: socket hangup even though I'm providing U/P.

**Comment by dvand** [comment]
These are the options i set. I didn't do a lot of experimentation to see
which ones were necessary or not

var options =
{secureProtocol:'TLSv1_method',rejectUnauthorized:'false',cipher:'AES256-SHA'};
